ruby-sample/rails-sample/media_app/config/routes.rb
Rails.application.routes.draw do
  resources :slots

end

ruby-sample/rails-sample/media_app/app/models/slot.rb
class Slot < ActiveRecord::Base
end

ruby-sample/rails-sample/media_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ruby-sample/rails-sample/media_app/app/controllers/slots_controller.rb
class SlotsController < ApplicationController
  before_action :set_slot, only: [:show, :edit, :update, :destroy]

  # GET /slots
  def index
    @slots = Slot.all
  end

  # GET /slots/1
  def show
  end

  # GET /slots/new
  def new
    @slot = Slot.new
  end

  # GET /slots/1/edit
  def edit
  end

  # POST /slots
  def create
    @slot = Slot.new(slot_params)

    if @slot.save
      redirect_to @slot, notice: 'Slot was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /slots/1
  def update
    if @slot.update(slot_params)
      redirect_to @slot, notice: 'Slot was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /slots/1
  def destroy
    @slot.destroy
    redirect_to slots_url, notice: 'Slot was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slot
      @slot = Slot.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def slot_params
      params.require(:slot).permit(:name, :value)
    end
end

ruby-sample/rails-sample/media_app/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby-sample/rails-sample/media_app/app/helpers/slots_helper.rb
module SlotsHelper
end

ruby-sample/rails-sample/media_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MediaApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

ruby-sample/rails-sample/media_app/app/views/slots/_form.html.erb
<%= form_for(@slot) do |f| %>
  <% if @slot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@slot.errors.count, "error") %> prohibited this slot from being saved:</h2>

      <ul>
      <% @slot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_area :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ruby-sample/rails-sample/media_app/app/views/slots/edit.html.erb
<h1>Editing Slot</h1>

<%= render 'form' %>

<%= link_to 'Show', @slot %> |
<%= link_to 'Back', slots_path %>

ruby-sample/rails-sample/media_app/app/views/slots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Slots</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @slots.each do |slot| %>
      <tr>
        <td><%= slot.name %></td>
        <td><%= slot.value %></td>
        <td><%= link_to 'Show', slot %></td>
        <td><%= link_to 'Edit', edit_slot_path(slot) %></td>
        <td><%= link_to 'Destroy', slot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Slot', new_slot_path %>

ruby-sample/rails-sample/media_app/app/views/slots/new.html.erb
<h1>New Slot</h1>

<%= render 'form' %>

<%= link_to 'Back', slots_path %>

ruby-sample/rails-sample/media_app/app/views/slots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @slot.name %>
</p>

<p>
  <strong>Value:</strong>
  <%= @slot.value %>
</p>

<%= link_to 'Edit', edit_slot_path(@slot) %> |
<%= link_to 'Back', slots_path %>